### PR TITLE
Redirect unless https proto

### LINKED ISSUE #67: Need for redirectUnlessHttpsProto
This feature has been previously requested, then implemented and since regressed.

Original feature request: https://github.com/vfarcic/docker-flow-proxy/issues/351
Implementation: https://github.com/vfarcic/docker-flow-proxy/pull/374
Caused a problem: #4 
Regression: #5 

To sum up the original feature request, there is a need to perform a redirect _unless_ the `X-Forwarded-Proto: https` header is present. Apparently, solving it by applying inverse logic based on the current query parameter `redirectWhenHttpProto` is not sufficient, ref. #4 .

So I'm suggesting a new service query parameter `redirectUnlessHttpsProto` to fix exactly our problem, avoiding making any bad surprises for anyone else. I'd be happy to supply a PR if there's general agreement that this is the way to go.

### PR DESCRIPTION
**Pull request by audunhalland**
Implements the required change in order to fix #67 .

A new service query parameter `redirectUnlessHttpsProto` is added, enabling a previously (short-term) supported feature, that was since removed.

### CODE REVIEW

**Comment by audunhalland** [comment]
Build failure, error message appears to be unrelated to my changes.

**Comment by thomasjpfan** [comment]
Can you force the CI to run again with:

```bash
git commit --allow-empty -m "Trigger CI"
```

**Comment by audunhalland** [comment]
@thomasjpfan build error looks related to https://github.com/sirupsen/logrus/issues/824. Looks like some windows port thingy that I'm not familiar with and also I'm not a golang expert at all so I'm not sure how to fix it.

**Comment by dgsb** [comment]
@audunhalland this is indeed a new dependency which has been added in order to perform colored output on windows. To fix your build for windows target a simple go get should be enough to fix your build.

**Comment by audunhalland** [comment]
After a bit of searching in the dark it seems to fail inside the cross-compile container `vfarcic/gox`. The entrypoint of that image is

```
#!/usr/bin/env bash

go get -d -v -t

gox --output="$1_{{.OS}}_{{.Arch}}" -osarch="linux/amd64 linux/arm windows/amd64 darwin/amd64"
```

Is there some conditional arch-based library selection going on so that it calling `go get` "outside" `gox ...` won't work?

**Comment by thomasjpfan** [comment]
@audunhalland Thanks for looking into it. It seems `go get` seems to avoid getting windows dependencies when ran in a non-windows environment.

I have been considering moving this project to go modules to avoid build issue such as this. Fixing the build process is out of scope for this PR. I will fix the build process in another PR, so that this PR can proceed.

**Comment by thomasjpfan** [comment]
@audunhalland Can you merge the master branch with this PR? This should fix the build issues.

**Pull request merged**
